import turtle
class human:
    def draw1(self):
        turtle.pensize(20)
        turtle.speed(0)
        turtle.up()
        turtle.goto(100, 100)
        turtle.down()
        turtle.circle(60)
        turtle.right(90)
        turtle.forward(200)
        turtle.up()
        turtle.right(180)
        turtle.goto(100, 75)
        turtle.down()
        turtle.right(135)
        turtle.forward(90)
        turtle.left(180)
        turtle.forward(90)
        turtle.left(85)
        turtle.forward(90)
        turtle.left(180)
        turtle.forward(90)
        turtle.right(130)
        turtle.forward(180)
        turtle.left(45)
        turtle.forward(90)
        turtle.left(180)
        turtle.forward(90)
        turtle.left(90)
        turtle.forward(90)
        turtle.up()
        turtle.goto(-200, -200)
        turtle.down()
        turtle.right(225)
        turtle.getscreen()._root.mainloop()

